export const itemsData = [
  { id: 1, text: "Martini Rosso/Bianco", price: 5.1, percent: 19 },
  { id: 2, text: "Cynar Soda", price: 5.2, percent: 19 },
  { id: 3, text: "Sherry", price: 4.2, percent: 19 },
  { id: 4, text: "Prosecco Aperol", price: 5.9, percent: 19 },
  { id: 5, text: "Bitterino", price: 4.6, percent: 19 },
  { id: 6, text: "Campari Soda", price: 5.9, percent: 19 },
  { id: 7, text: "Campari Orange", price: 5.9, percent: 19 },
  { id: 8, text: "Prosecco", price: 5.6, percent: 19 },
  { id: 9, text: "Aperol Spritzz", price: 6.9, percent: 19 },
  {
    id: 10,
    text: "Caprese Napoletana",
    price: 11.1,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 11,
    text: "Insalata Di Rucola",
    price: 8.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 12,
    text: "Antipasto Dello Verdure",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 13,
    text: "Carpaccio Di Manzo",
    price: 12.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 14,
    text: "Insalata Di Mare",
    price: 12.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 15,
    text: "Formaggi Misti",
    price: 13.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 17,
    text: "Rucola Gamberetti",
    price: 12.1,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 18,
    text: "Antipasto Italiano",
    price: 13.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 19,
    text: "Insalata Di Rucola Con Gamberetti",
    price: 12.1,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 20,
    text: "Minestrone",
    price: 5.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 22,
    text: "Crema Di Pomodoro",
    price: 5.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 23,
    text: "Tortellini In Brodo",
    price: 5.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 31,
    text: "Spag. Al Pomodoro",
    price: 9.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 32,
    text: "Spag. Bolognese",
    price: 10.8,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 33,
    text: "Spag. Aglio & Oglio",
    price: 9.1,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 34,
    text: "Spag. Alla Carbonara",
    price: 11.3,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 35,
    text: "Spag. Frutti Di Mare",
    price: 14.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 37,
    text: "Penne Al Gorgonzola e Spinaci",
    price: 11.2,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 38,
    text: "Penne Brocolli",
    price: 12.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 39,
    text: "Tortelini Alla Panna",
    price: 11.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 40,
    text: "Penne Arabiata",
    price: 10.8,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 41,
    text: "Bruschetta",
    price: 6.5,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 44,
    text: "Caprese Pizza",
    price: 10.6,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 43,
    text: "Penne Formaggi",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 49,
    text: "Pizzabrot",
    price: 4.5,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 50,
    text: "Gnocchi Alla Sorentina",
    price: 10.8,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 51,
    text: "Lasagne Al Forno",
    price: 10.4,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 52,
    text: "Penne Al Forno",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 53,
    text: "Tortelini Al Forno",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 54,
    text: "Gnocchi Al Forno",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 55,
    text: "Ravioli ripieni con Riccotta e Spinaci",
    price: 11.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 56,
    text: "Fettuccine al Salmone",
    price: 12.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 57,
    text: "Ravioli ripieni al Salmone",
    price: 11.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 58,
    text: "Cappelletti Ripieni con Gorgonzola",
    price: 11.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 59,
    text: "Ravioli Ripieni al Porcini",
    price: 11.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 60,
    text: "Tris di Pasta",
    price: 11.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 62,
    text: "Tagliatelle al pesto",
    price: 12.4,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 63,
    text: "Tonno mit Zwiebel",
    price: 11.1,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 72,
    text: "Insalata verde",
    price: 5.6,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 73,
    text: "Insalata di pomodoro",
    price: 5.4,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 74,
    text: "Insalata mista",
    price: 6.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 76,
    text: "Insalata di pomodoro con tonno e cipolla",
    price: 6.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 77,
    text: "Insalata mista con tonno",
    price: 8.2,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 78,
    text: "Insalata della casa",
    price: 13.4,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 79,
    text: "Piiza Hawai",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 80,
    text: "Pizza Margherita",
    price: 8.9,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 81,
    text: "Pizza della Casa",
    price: 13.5,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 82,
    text: "Pizza Prosciutto",
    price: 9.4,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 83,
    text: "Pizza Don Padrino",
    price: 13.5,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 84,
    text: "Pizza Bianca",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 85,
    text: "Pizza Funghi",
    price: 9.4,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 86,
    text: "Pizza Salami",
    price: 9.4,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 87,
    text: "Pizza Sardele",
    price: 9.4,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 88,
    text: "Pizza Tonno",
    price: 10.6,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 89,
    text: "Pizza Pesto",
    price: 9.4,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 90,
    text: "Pizza Capricciosa",
    price: 10.7,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 91,
    text: "Pizza Gorgonzola e Spinaci",
    price: 10.5,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 93,
    text: "Pizza Siciliana",
    price: 11.2,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 94,
    text: "Pizza Frutti di Mare",
    price: 13.9,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 96,
    text: "Pizza Quattro Stagioni",
    price: 10.9,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 97,
    text: "Pizza Vegetariana",
    price: 11.2,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 98,
    text: "Pizza Diavolo",
    price: 10.8,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  {
    id: 99,
    text: "Pizza Calzone",
    price: 11.3,
    percent: 7,
    category: "pizza",
    boss: true,
    pizza: true,
  },
  { id: 100, text: "Coca 0.3", price: 3.3, percent: 19 },
  { id: 101, text: "Fanta 0.3", price: 3.3, percent: 19 },
  { id: 102, text: "Spezi 0.3", price: 3.3, percent: 19 },
  { id: 103, text: "Bitter Lemon 0.3", price: 3.8, percent: 19 },
  { id: 104, text: "Saft 0.3", price: 3.6, percent: 19 },
  {
    id: 105,
    text: "Saftschorle 0.3",
    price: 3.3,
    percent: 19,
    options: ["Orange", "Maracuja", "Apfel", "Johannes"],
  },
  { id: 106, text: "Süße Sprudel 0.3", price: 3.3, percent: 19 },
  { id: 108, text: "Vio 0.25", price: 3.1, percent: 19 },
  { id: 210, text: "Vio 0.75", price: 5.1, percent: 19 },
  { id: 109, text: "Teinacher 0.25", price: 3.1, percent: 19 },
  { id: 110, text: "Pellegrino 0.75", price: 5.2, percent: 19 },
  { id: 111, text: "Cola 0.4", price: 4.1, percent: 19 },
  { id: 112, text: "Fanta 0.4", price: 4.1, percent: 19 },
  { id: 113, text: "Spezi 0.4", price: 4.1, percent: 19 },
  { id: 114, text: "Bitter Lemon 0.4", price: 4.5, percent: 19 },
  { id: 115, text: "Bitter Lemon 0.4", price: 4.5, percent: 19 },
  { id: 116, text: "Apfelsaftschorle 0.4", price: 4.1, percent: 19 },
  { id: 117, text: "Säfte 0.4", price: 4.4, percent: 19 },
  { id: 118, text: "Süße Sprudel 0.4", price: 4.1, percent: 19 },
  { id: 119, text: "Cola Light 0.3", price: 3.8, percent: 19 },
  { id: 119, text: "Cola Light 0.3", price: 3.8, percent: 19 },
  { id: 120, text: "Cola Light 0.4", price: 4.5, percent: 19 },
  {
    id: 198,
    text: "Saftschorle 0.3",
    price: 3.3,
    percent: 19,
    options: ["Orange", "Maracuja", "Apfel", "Johannes"],
  },
  {
    id: 199,
    text: "Saftschorle 0.4",
    price: 4.1,
    percent: 19,
    options: ["Orange", "Maracuja", "Apfel", "Johannes"],
  },
  { id: 211, text: "Teinacher 0.5", price: 4.6, percent: 19 },
  { id: 121, text: "Pils 0.3", price: 3.5, percent: 19 },
  { id: 122, text: "Pils 0.4", price: 3.9, percent: 19 },
  { id: 123, text: "Radler 0.3", price: 3.3, percent: 19 },
  { id: 124, text: "Radler 0.4", price: 3.7, percent: 19 },
  { id: 125, text: "Weissbier 0.5", price: 4.3, percent: 19 },
  { id: 126, text: "Kristall 0.5", price: 4.3, percent: 19 },
  { id: 127, text: "Dunkel 0.5", price: 4.3, percent: 19 },
  { id: 128, text: "Alkoholfrei 0.5", price: 4.3, percent: 19 },
  { id: 129, text: "Diesel/Russ 0.5", price: 4.5, percent: 19 },
  { id: 130, text: "Vino Bianco 0.2", price: 6.3, percent: 19 },
  { id: 135, text: "Vino Bianco 0.2", price: 6.3, percent: 19 },
  { id: 142, text: "Vino Rosso 0.2", price: 6.3, percent: 19 },
  {
    id: 145,
    text: "Piccata Milanese",
    price: 23.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 146,
    text: "Paillard - Steak",
    price: 23.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 147,
    text: "Saltimbocca alla Romana",
    price: 24.9,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 148,
    text: "Scaloppina al Vino Bianco/Limone",
    price: 24.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 149,
    text: "Scaloppina al Limone",
    price: 24.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 150,
    text: "Filetto di Manzo al Gorgonzola",
    price: 34.0,
    percent: 7,
    percent: 19,
    options: ["medium", "medium-", "medium+"],
    category: "pizza",
    boss: true,
  },
  {
    id: 151,
    text: "Filetto di Manzo Grill",
    price: 33.0,
    percent: 7,
    percent: 19,
    options: ["medium", "medium-", "medium+"],
    category: "pizza",
    boss: true,
  },
  {
    id: 152,
    text: "Filetto di Manzo al Pepe",
    price: 34.0,
    percent: 7,
    percent: 19,
    options: ["medium", "medium-", "medium+"],
    category: "pizza",
    boss: true,
  },
  {
    id: 153,
    text: "Calamari alla Grill",
    price: 22.0,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 154,
    text: "Rana Pescatrice ",
    price: 28.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 155,
    text: "Rana Pescatrice ",
    price: 28.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 158,
    text: "Gamberoni alla Griglia ",
    price: 26.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 159,
    text: "Rana Pescatrice al Pepe ",
    price: 28.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 160,
    text: "Amaretto 0.2",
    price: 4.2,
    percent: 19,
    category: "pizza",
  },
  { id: 161, text: "Sambuca 0.2", price: 4.2, percent: 19 },
  { id: 162, text: "Cynar Spirituosen 0.2", price: 4.2, percent: 19 },
  { id: 163, text: "Fernet Branca 0.2", price: 4.2, percent: 19 },
  { id: 164, text: "Ramazzotti 0.2", price: 4.2, percent: 19 },
  { id: 165, text: "Averna 0.2", price: 4.2, percent: 19 },
  { id: 166, text: "Vecchia Romagnia 0.2", price: 4.2, percent: 19 },
  { id: 167, text: "Amaro Montenegro 0.2", price: 4.2, percent: 19 },
  { id: 168, text: "Limoncello 0.2", price: 4.2, percent: 19 },
  { id: 169, text: "Grappa 0.2", price: 6.5, percent: 19 },
  {
    id: 175,
    text: "Salmone alla Griglia",
    price: 24.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  { id: 180, text: "Tartufo", price: 5.9, percent: 7, boss: true },
  { id: 181, text: "Cassata", price: 5.9, percent: 7, boss: true },
  { id: 182, text: "Tiramisu", price: 5.9, percent: 7, boss: true },
  { id: 183, text: "Crem Caramel", price: 5.9, percent: 7, boss: true },
  { id: 184, text: "Panna Cotta", price: 5.9, percent: 7, boss: true },
  { id: 190, text: "Espresso", price: 2.3, percent: 19 },
  { id: 191, text: "Kaffee", price: 3.0, percent: 19 },
  { id: 192, text: "Espresso Corretto", price: 3.3, percent: 19 },
  { id: 193, text: "Capuccino", price: 3.3, percent: 19 },
  { id: 194, text: "Tee mit Zitrone und Honig", price: 3.6, percent: 19 },
  { id: 195, text: "Tee mit Rum", price: 3.3, percent: 19 },
  { id: 196, text: "Doppio Espresso", price: 3.5, percent: 19 },
  { id: 197, text: "Latte Macchiato", price: 3.5, percent: 19 },
  { id: 202, text: "Williams 0.2", price: 4.5, percent: 19 },
  { id: 209, text: "Vino 0.1", price: 3.8, percent: 19 },
  {
    id: 501,
    text: "M1",
    price: 11.5,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  {
    id: 502,
    text: "M2",
    price: 12.0,
    percent: 7,
    category: "pizza",
    boss: true,
  },
  { id: 144, text: "Montepulciano 0.2", price: 6.3, percent: 19 },
  { id: 138, text: "Chianti 0.2", price: 6.3, percent: 19 },
  { id: 999, text: "Nero D'avola 0.2", price: 6.3, percent: 19 },
  { id: 998, text: "Primitivo 0.2", price: 6.3, percent: 19 },
  { id: 140, text: "Lambrusco 0.2", price: 6.3, percent: 19 },
  { id: 132, text: "Frascati 0.2", price: 6.3, percent: 19 },
  { id: 136, text: "Pinot Grigio 0.2", price: 6.3, percent: 19 },
  { id: 137, text: "Verdiccho 0.2", price: 6.3, percent: 19 },
  { id: 131, text: "Frizzantino 0.2", price: 6.3, percent: 19 },
  { id: 134, text: "Rosatello 0.2", price: 6.3, percent: 19 },
  { id: 133, text: "Schorle 0.2", price: 5.3, percent: 19 },
  { id: 997, text: "Leverano Weis/Rot/Rosse 0.2", price: 7.9, percent: 19 },
  { id: 996, text: "Leverano Weis/Rot/Rosse 0.75", price: 26.5, percent: 19 },
  { id: 995, text: "Aglianic Caudium 0.75", price: 38.5, percent: 19 },
  { id: 994, text: "Aglianic Caudium 0.2", price: 13.5, percent: 19 },
  { id: 993, text: "Malvasia 0.75", price: 28.5, percent: 19 },
  { id: 992, text: "Malvasia 0.2", price: 9.8, percent: 19 },
  {
    id: 991,
    text: "Ca de Frati Weis/Rot/Rosse 0.75",
    price: 36.5,
    percent: 19,
  },
];
